// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlbuWC5hmmpvdMr0D4XnwVxZOG0a32KG4',
    appId: '1:930290524196:web:232ea749a7b139a77878b1',
    messagingSenderId: '930290524196',
    projectId: 'motor-test-stand',
    authDomain: 'motor-test-stand.firebaseapp.com',
    databaseURL: 'https://motor-test-stand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motor-test-stand.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzX9HA-aXLfDaSqdwqA4eQSE5xJm7-adU',
    appId: '1:930290524196:android:85b9ccd4845a16067878b1',
    messagingSenderId: '930290524196',
    projectId: 'motor-test-stand',
    databaseURL: 'https://motor-test-stand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motor-test-stand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwS0AYMMYXA9O7hRA8M7i-cjH0gb-fHqs',
    appId: '1:930290524196:ios:b3d760b16099ef007878b1',
    messagingSenderId: '930290524196',
    projectId: 'motor-test-stand',
    databaseURL: 'https://motor-test-stand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motor-test-stand.appspot.com',
    iosBundleId: 'com.example.mechprojectdcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwS0AYMMYXA9O7hRA8M7i-cjH0gb-fHqs',
    appId: '1:930290524196:ios:b3d760b16099ef007878b1',
    messagingSenderId: '930290524196',
    projectId: 'motor-test-stand',
    databaseURL: 'https://motor-test-stand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motor-test-stand.appspot.com',
    iosBundleId: 'com.example.mechprojectdcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlbuWC5hmmpvdMr0D4XnwVxZOG0a32KG4',
    appId: '1:930290524196:web:f3f6028b5db86b3e7878b1',
    messagingSenderId: '930290524196',
    projectId: 'motor-test-stand',
    authDomain: 'motor-test-stand.firebaseapp.com',
    databaseURL: 'https://motor-test-stand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motor-test-stand.appspot.com',
  );

}